INSERT INTO shiva_db_tranasation_purchaseOrder (
    CURRENCY_code,
    GROSS_AMOUNT,
    NET_AMOUNT,
    TAX_AMOUNT,
    NODE_KEY,
    PO_ID,
    PARTNER_GUID_NODE_KEY,
    LIFECYCLE_STATUS,
    OVERALL_STATUS
  )
VALUES (
    'CURRENCY_code:NVARCHAR(3)',
    'GROSS_AMOUNT:DECIMAL(10, 2)',
    'NET_AMOUNT:DECIMAL(10, 2)',
    'TAX_AMOUNT:DECIMAL(10, 2)',
    'NODE_KEY:NVARCHAR(32)',
    'PO_ID:NVARCHAR(10)',
    'PARTNER_GUID_NODE_KEY:NVARCHAR(32)',
    'LIFECYCLE_STATUS:NVARCHAR(1)',
    'OVERALL_STATUS:NVARCHAR(2)'
  );